//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
        public string AgeRating { get; set; }
        public string Compatability { get; set; }
        public string CoverImagePath { get; set; }
        public string XeniaBuild { get; set; }
    }
}
